language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t kintama510/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kintama510/react-test npm test

after_success:
    - docker build -t kintama510/multi-client ./client
    - docker build -t kintama510/multi-nginx ./nginx
    - docker build -t kintama510/multi-server ./server
    - docker build -t kintama510/multi-worker ./worker
    # Login into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push kintama510/multi-client
    - docker push kintama510/multi-nginx
    - docker push kintama510/multi-server
    - docker push kintama510/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: docker-multi
    env: DockerMulti-env
    bucet_name: elasticbeanstalk-us-east-2-393787123670
    bucket_path: multi_docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

       





